services:
  - type: web
    name: crypto
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn crypto:app
    envVars:
      - key: FLASK_ENV
        value: production
